version: "2"
run:
  modules-download-mode: readonly
  timeout: 10m
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  exclusions:
    rules:
    - linters:
        - revive
      text: "^package-comments"
formatters:
  enable:
    - goimports
issues:
  max-issues-per-linter: 0
  max-same-issues: 0