version: "2"
run:
  modules-download-mode: readonly
  timeout: 10m
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  exclusions:
    rules:
    - linters:
        - revive
      text: "^package-comments"
    # TODO: remove this exclusion when metalv1 is
    # removed from the SDK & CLI
    - path: internal/metalv1/metalv1.go
      text: "SA4000:"
formatters:
  enable:
    - goimports
issues:
  max-issues-per-linter: 0
  max-same-issues: 0