# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    binary: equinix
    ldflags:
      - -s -w -X github.com/equinix/cli/internal/version.Version={{.Version}}

    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - 'zip'
    name_template: "equinix-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
checksum:
  name_template: "equinix_{{ .Version }}_checksums.txt"
release:
  mode: "keep-existing"

homebrew_casks:
  - name: equinix
    homepage: "https://docs.equinix.com/"
    description: "Official Equinix CLI"
    license: "MIT"
    commit_msg_template: "Brew formula update for {{ .Binary }} version {{ .Tag }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equinix"]
          end
    repository:
      owner: equinix
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
