# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    binary: equinix
    ldflags:
      - -s -w -X github.com/equinix/cli/internal/version.Version={{.Version}}

    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - 'binary'
    name_template: "equinix-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "equinix_{{ .Version }}_checksums.txt"
release:
  mode: "keep-existing"
